labels: [idea]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Share Your Ideas

        Have an idea to improve the Claude Code Extended Framework? We'd love to hear it!

  - type: textarea
    id: idea
    attributes:
      label: Idea Description
      description: Describe your idea in detail
      placeholder: What improvement or feature are you suggesting?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: What challenge or pain point would this address?

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement this?
      placeholder: Describe how this would work

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which area does this relate to?
      options:
        - SPARC Methodology
        - Multi-Agent Coordination
        - PM System (CCPM)
        - Documentation
        - GitHub Automation
        - Shell Scripts
        - MCP Integration
        - Other
    validations:
      required: true

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      options:
        - label: I'd be willing to implement this idea
        - label: I'd be willing to help test this

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references
